# SPDX-FileCopyrightText: 2014 Istituto Nazionale di Fisica Nucleare
#
# SPDX-License-Identifier: Apache-2.0

management:
  health:
    redis:
      enabled: true
      
spring:
  data:
    redis:
      host: ${STORM_WEBDAV_REDIS_HOST:localhost}
      port: ${STORM_WEBDAV_REDIS_PORT:6379}
      password: ${STORM_WEBDAV_REDIS_PASSWORD:}
 
  session:
    store-type: redis
