server:
  jetty:
    accesslog:
      enabled: false

storm:
  sa:
    config-dir: src/test/resources/conf/sa.d
  tls:
    trust-anchors-dir: src/test/resources/trust-anchors
  voms:
    trust-store:
      dir: src/test/resources/vomsdir