storm:
  authz:
    policies:
    - sa: fine_grained_authz
      actions:
      - list
      - read
      effect: permit
      description: Grant read access to selected vo users
      principals:
      - type: anyone
    - sa: example
      actions:
      - all
      effect: permit
      description: Grant read/write access to WLCG VOMS vo users
      principals:
      - type: vo
        params:
          vo: wlcg
      