storm:
  authz:
    policies:
    - sa: fine_grained_authz
      actions:
      - list
      - read
      effect: permit
      description: Grant read access to selected vo users
      principals:
      - type: vo
        params:
          vo: test.vo
      - type: vo
        params:
          vo: dteam