# SPDX-FileCopyrightText: 2014 Istituto Nazionale di Fisica Nucleare
#
# SPDX-License-Identifier: Apache-2.0

oauth:
  
  issuers:
    - name: iam-test
      issuer: https://iam-test.indigo-datacloud.eu/
    - name: iam-wlcg
      issuer: https://wlcg.cloud.cnaf.infn.it/
    - name: iam-local
      issuer: https://iam.local.io/