spring:
  main:
    banner-mode: "off"
  security:
    oauth2:
      client:
        provider:
          wlcg:
            issuer-uri: https://wlcg.cloud.cnaf.infn.it/
          escape:
            issuer-uri: https://iam-escape.cloud.cnaf.infn.it/
          indigo:
            issuer-uri: https://iam-test.indigo-datacloud.eu/
server:
  address: ${STORM_WEBDAV_SERVER_ADDRESS:0.0.0.0}
  error:
    whitelabel:
      enabled: false
  
  jetty:
    max-threads: ${storm.connector.max-connections}
     

tpc:
  tlsProtocol: ${STORM_WEBDAV_TPC_TLS_PROTOCOL:TLSv1.2}
  maxConnections: ${STORM_WEBDAV_TPC_MAX_CONNECTIONS:50}
  max-connections-per-route: ${STORM_WEBDAV_TPC_MAX_CONNECTIONS_PER_ROUTE:25}
  timeout-in-secs: ${STORM_WEBDAV_TPC_TIMEOUT_IN_SECS:5}
  verifyChecksum: ${STORM_WEBDAV_TPC_VERIFY_CHECKSUM:false}
  reportDelaySecs: ${STORM_WEBDAV_TPC_REPORT_DELAY_SECS:5}
  httpClientSocketBufferSize: ${STORM_WEBDAV_TPC_HTTP_CLIENT_SOCKET_BUFFER_SIZE:8192}
  localFileBufferSize: ${STORM_WEBDAV_TPC_LOCAL_FILE_BUFFER_SIZE:4096}
  use-conscrypt: ${STORM_WEBDAV_TPC_USE_CONSCRYPT:false}
  enable-tls-client-auth: ${STORM_WEBDAV_TPC_ENABLE_TLS_CLIENT_AUTH:false}
  

oauth:
  refresh-period-minutes: 60
  issuers:

storm:
  checksum-strategy: early
  
  access-log-configuration-path: ${STORM_WEBDAV_ACCESS_LOG_CONFIGURATION:}
  
  hostnames:
    - ${STORM_WEBDAV_HOSTNAME_0:${server.address}}
    - ${STORM_WEBDAV_HOSTNAME_1:}
    - ${STORM_WEBDAV_HOSTNAME_2:}
    - ${STORM_WEBDAV_HOSTNAME_3:}

  authz:
    disabled: false

  checksum-filter:
    enabled: ${STORM_WEBDAV_CHECKSUM_FILTER_ENABLED:true}
    
  macaroon-filter:
    enabled: ${STORM_WEBDAV_MACAROON_FILTER_ENABLED:true}
    
  connector:
    port:  ${STORM_WEBDAV_HTTP_PORT:8085}
    secure-port: ${STORM_WEBDAV_HTTPS_PORT:8443}
    max-connections: ${STORM_WEBDAV_MAX_CONNECTIONS:300}
    max-queue-size: ${STORM_WEBDAV_MAX_QUEUE_SIZE:900}
    max-idle-time-msec: ${STORM_WEBDAV_CONNECTOR_MAX_IDLE_TIME:30000} 
    
  tls:
    certificatePath: ${STORM_WEBDAV_CERTIFICATE_PATH:/etc/grid-security/storm-webdav/hostcert.pem}
    privateKeyPath: ${STORM_WEBDAV_PRIVATE_KEY_PATH:/etc/grid-security/storm-webdav/hostkey.pem}
    trustAnchorsDir: ${STORM_WEBDAV_TRUST_ANCHORS_DIR:/etc/grid-security/certificates}
    trustAnchorsRefreshIntervalSecs: ${STORM_WEBDAV_TRUST_ANCHORS_REFRESH_INTERVAL:86400}
    requireClientCert: ${STORM_WEBDAV_REQUIRE_CLIENT_CERT:true}
    use-conscrypt: ${STORM_WEBDAV_USE_CONSCRYPT:false}
    enable-http2: ${STORM_WEBDAV_ENABLE_HTTP2:false}
  
  sa:
    configDir: ${STORM_WEBDAV_SA_CONFIG_DIR:/etc/storm/webdav/sa.d}
  
  voMapFiles:
    configDir: ${STORM_WEBDAV_VO_MAP_FILES_CONFIG_DIR:/etc/storm/webdav/vo-mapfiles.d}
    enabled: ${STORM_WEBDAV_VO_MAP_FILES_ENABLE:false}
    refreshIntervalSec: ${STORM_WEBDAV_VO_MAP_FILES_REFRESH_INTERVAL:21600}
  
  authz-server:
    enabled: ${STORM_WEBDAV_AUTHZ_SERVER_ENABLE:true}
    issuer: ${STORM_WEBDAV_AUTHZ_SERVER_ISSUER:https://${storm.hostnames[0]}:${storm.connector.secure-port}}
    secret: ${STORM_WEBDAV_AUTHZ_SERVER_SECRET:${random.value}}
    max-token-lifetime-sec: ${STORM_WEBDAV_AUTHZ_SERVER_MAX_TOKEN_LIFETIME_SEC:43200}
  
  voms:
    trust-store:
      dir:  ${STORM_WEBDAV_VOMS_TRUST_STORE_DIR:/etc/grid-security/vomsdir}
      refresh-interval-sec: ${STORM_WEBDAV_VOMS_TRUST_STORE_REFRESH_INTERVAL_SEC:43200}
      
    cache:
      enabled: ${STORM_WEBDAV_VOMS_CACHE_ENABLE:true}
      entry-lifetime-sec: ${STORM_WEBDAV_VOMS_CACHE_ENTRY_LIFETIME_SEC:300}