# SPDX-FileCopyrightText: 2014 Istituto Nazionale di Fisica Nucleare
#
# SPDX-License-Identifier: Apache-2.0

oauth:
  issuers:
    - name: egi-checkin
      issuer: https://egi-checkin.example/
    - name: dev
      issuer: https://iam-dev.cloud.cnaf.infn.it/