oauth:
  issuers:
    - name: wlcg
      issuer: https://wlcg.cloud.cnaf.infn.it/

storm:
  authz:
    policies:
    - sa: fga
      actions:
      - list
      - read
      effect: permit
      description: Grant read access to anyone to the public area
      paths:
      - /public/**
      principals:
      - type: anyone
    - sa: fga
      actions:
      - all
      effect: permit
      description: Grant read/write access to test.vo VOMS users
      principals:
      - type: vo
        params:
          vo: test.vo
    # ToDo: Set proper policy for
    # "Put/Get works with locally issued token fga" tests
    - sa: fga
      actions:
      - all
      effect: permit
      description: Grant all access to test0 oidc-subject
      principals:
      - type: oidc-subject
        params:
            iss: https://storm.test.example:8443
            sub: CN=test0,O=IGI,C=IT
