version: "3"

volumes:
  trustanchors:
  cabundle:
  saconfig:
  storage:
  storage2:
  hostcert:
  mapfilesconfig:

services:
  trust:
    image: indigoiam/trustanchors:latest
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - cabundle:/etc/pki
    environment:
      FORCE_TRUST_ANCHORS_UPDATE: 1

  webdav-setup:
    image: cnafsd/storm-webdav
    privileged: true
    environment:
      TZ: UTC

    volumes:
      - ./assets/certs/:/certs:ro
      - ./assets/etc/storm/webdav/sa.d/:/sa.d:ro
      - hostcert:/etc/grid-security
      - saconfig:/etc/storm/webdav/sa.d
      - mapfilesconfig:/etc/storm/webdav/vo-mapfiles.d
      - ./assets/scripts:/scripts:ro
      - ./assets/etc/storm/webdav/vo-mapfiles.d/:/vo-mapfiles.d:ro
      - storage:/storage

    entrypoint:
      - /scripts/setup.sh

  webdav:
    image: cnafsd/storm-webdav
    privileged: true
    dns_search: example
    ports:
      - "8443:8443"
      - "8085:8085"
      - "9444:1044"

    depends_on:
      - trust
      - webdav-setup

    environment:
      TZ: UTC
      STORM_WEBDAV_REQUIRE_CLIENT_CERT: "false"
      STORM_WEBDAV_HOSTNAME_0: storm.example
      STORM_WEBDAV_USE_CONSCRYPT: "true"
      STORM_WEBDAV_JVM_OPTS: -Dspring.profiles.active=test
      DONT_UNPACK_TARBALL: "true"
      #DEBUG: y
      #DEBUG_SUSPEND: y

    volumes:
      - storage:/storage
      - hostcert:/etc/grid-security
      - saconfig:/etc/storm/webdav/sa.d
      - mapfilesconfig:/etc/storm/webdav/vo-mapfiles.d
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - ./assets/vomsdir:/etc/grid-security/vomsdir:ro
      - ./assets/scripts:/scripts:ro
      - ${HOME}/git/storm-webdav:/code:ro

    entrypoint:
      - /scripts/run.sh

    networks:
      default:
        aliases:
          - storm.example

  ts:
    image: italiangrid/storm-webdav-ts:latest
    environment:
      - IAM_ACCESS_TOKEN
      - TZ=UTC 
      - DAV_HOST=storm.example
      - REMOTE_DAV_HOST=storm-alias.example

    depends_on:
      - webdav 

    volumes:
      - storage:/storage
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - ./assets/vomses:/etc/vomses:ro
      - ./assets/vomsdir:/etc/grid-security/vomsdir
      - ./assets/scripts:/scripts:ro
      - ./assets/usercerts/:/usercerts:ro
      - ${HOME}/git/storm-webdav:/code:ro

    entrypoint:  sleep infinity
    
    #entrypoint: 
    # - /scripts/wait-and-run-testsuite.sh

    networks:
      default:

  nginx:
    image: storm2/ngx-voms:latest
    dns_search: example 

    ports:
      - "9553:443"

    depends_on:
      - trust
      - webdav-setup

    environment:
      TZ: UTC
      X509_VOMS_DIR: /vomsdir

    volumes:
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - ./assets/certs/hostcert.pem:/etc/grid-security/hostcert.pem
      - ./assets/certs/hostkey.pem:/etc/grid-security/hostkey.pem
      - ./assets/vomsdir:/vomsdir
      - ./assets/nginx/nginx.conf:/home/storm/local/openresty/nginx/conf/nginx.conf:ro
      - ./assets/nginx/srm.conf:/etc/nginx/conf.d/srm.conf:ro
      - storage2:/storage

    networks:
      default:
        aliases:
          - storm-alias.example
