volumes:
  trustanchors:
  cabundle:
  vomsdir:
  certs:
  storage:


services:
  trust:
    build:
      context: docker
      dockerfile: Dockerfile.trust
    volumes:
      - trustanchors:/trust-anchors
      - cabundle:/etc/pki
      - vomsdir:/vomsdir
      - certs:/certs

  storage-setup:
    image: ${WEBDAV_IMAGE}:${WEBDAV_IMAGE_TAG}
    environment:
      TZ: UTC

    volumes:
      - ./assets/scripts:/scripts:ro
      - ./assets/etc/storm/webdav/sa.d/:/etc/storm/webdav/sa.d/:ro
      - storage:/storage
    user: root
    entrypoint:
      - /scripts/init-storage.sh

  webdav:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
      - "8085:8085"

    depends_on:
      trust:
        condition: service_completed_successfully
      storage-setup:
        condition: service_completed_successfully

    environment:
      TZ: UTC
      STORM_WEBDAV_CERTIFICATE_PATH: /etc/grid-security/storm-webdav/storm_test_example.cert.pem
      STORM_WEBDAV_PRIVATE_KEY_PATH: /etc/grid-security/storm-webdav/storm_test_example.key.pem
      STORM_WEBDAV_REQUIRE_CLIENT_CERT: "false"
      STORM_WEBDAV_HOSTNAME_0: storm.test.example
      STORM_WEBDAV_AUTHZ_SERVER_ENABLE: true
      STORM_WEBDAV_AUTHZ_SERVER_ISSUER: https://storm.test.example:8443
      STORM_WEBDAV_JVM_OPTS: -Dspring.profiles.active=policies,issuers

    volumes:
      - storage:/storage
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - certs:/etc/grid-security/storm-webdav/:ro 
      - vomsdir:/etc/grid-security/vomsdir:ro
      - ./assets/scripts:/scripts:ro
      - ./assets/etc/storm/webdav/sa.d/:/etc/storm/webdav/sa.d/:ro
      - ./assets/etc/storm/webdav/config/application-policies.yml:/app/application-policies.yml:ro
      - ./assets/etc/storm/webdav/config/application-issuers.yml:/app/application-issuers.yml:ro
      - ../:/code:ro

    healthcheck:
      test: curl https://storm.test.example:8443/actuator/health --fail || exit 1
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

    networks:
      default:
        aliases:
          - storm.test.example

  ts:
    image: ${TS_IMAGE}:${TS_IMAGE_TAG}
    environment:
      - TZ=UTC
      - ROBOT_ARGS
      - OIDC_AGENT_ALIAS
      - OIDC_AGENT_SECRET
      - IAM_ACCESS_TOKEN

    depends_on:
      webdav:
        condition: service_healthy
      trust:
        condition: service_completed_successfully

    volumes:
      - storage:/storage
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - vomsdir:/etc/grid-security/vomsdir
      - certs:/usercerts
      - ./assets/scripts:/scripts:ro
      - ./assets/oidc-agent:/home/test/.config/oidc-agent
      - ../:/code:ro

    entrypoint:  sleep infinity

    networks:
      default:

  nginx:
    image: ${NGINX_IMAGE}:${NGINX_IMAGE_TAG}
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      webdav:
        condition: service_started
      trust:
        condition: service_completed_successfully

    environment:
      TZ: UTC
      X509_VOMS_DIR: /vomsdir

    volumes:
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - certs:/certs
      - vomsdir:/vomsdir
      - ./assets/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets/nginx/srm.conf:/etc/nginx/conf.d/srm.conf:ro

    networks:
      default:
        aliases:
          - storm-alias.test.example
