volumes:
  trustanchors:
  cabundle:
  storage:
  storage2:


services:
  trust:
    image: ${TRUST_IMAGE}:${TRUST_IMAGE_TAG}
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - cabundle:/etc/pki
    environment:
      FORCE_TRUST_ANCHORS_UPDATE: 1

  storage-setup:
    image: ${WEBDAV_IMAGE}:${WEBDAV_IMAGE_TAG}
    environment:
      TZ: UTC

    volumes:
      - ./assets/scripts:/scripts:ro
      - ./assets/etc/storm/webdav/sa.d/:/etc/storm/webdav/sa.d/:ro
      - storage:/storage
    user: root
    entrypoint:
      - /scripts/init-storage.sh

  webdav:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
      - "8085:8085"

    depends_on:
    #  trust:
    #    condition: service_completed_successfully
      storage-setup:
        condition: service_completed_successfully

    environment:
      TZ: UTC
      STORM_WEBDAV_REQUIRE_CLIENT_CERT: "false"
      STORM_WEBDAV_HOSTNAME_0: storm.test.example
      STORM_WEBDAV_JVM_OPTS: -Dspring.profiles.active=test,policies
      DONT_UNPACK_TARBALL: y

    volumes:
      - storage:/storage
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - ./assets/certs/:/etc/grid-security/storm-webdav/:ro 
      - ./assets/vomsdir:/etc/grid-security/vomsdir:ro
      - ./assets/scripts:/scripts:ro
      - ./assets/etc/storm/webdav/sa.d/:/etc/storm/webdav/sa.d/:ro
      - ./assets/etc/storm/webdav/config/application-policies.yml:/app/application-policies.yml:ro
      - ../:/code:ro

    networks:
      default:
        aliases:
          - storm.test.example

  ts:
    image: ${TS_IMAGE}:${TS_IMAGE_TAG}
    environment:
      - TZ=UTC
      - ROBOT_ARGS
      - IAM_CLIENT_ID
      - IAM_TOKEN_ENDPOINT=https://wlcg.cloud.cnaf.infn.it/token
      - IAM_ACCESS_TOKEN

    depends_on:
      webdav:
        condition: service_started
      trust:
        condition: service_completed_successfully

    volumes:
      - storage:/storage
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - ./assets/vomses:/etc/vomses:ro
      - ./assets/vomsdir:/etc/grid-security/vomsdir
      - ./assets/scripts:/scripts:ro
      - ./assets/usercerts/:/usercerts:ro
      - ../:/code:ro

    entrypoint:  sleep infinity

    networks:
      default:

  nginx:
    image: ${NGINX_IMAGE}:${NGINX_IMAGE_TAG}
    ports:
      - "443:443"

    depends_on:
      webdav:
        condition: service_started
      trust:
        condition: service_completed_successfully

    environment:
      TZ: UTC

    volumes:
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - ./assets/certs:/certs
      - ./assets/vomsdir:/vomsdir
      - ./assets/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets/nginx/srm.conf:/etc/nginx/conf.d/srm.conf:ro
      - storage2:/storage/oauth-authz

    networks:
      default:
        aliases:
          - storm-alias.test.example
