name: Build RPM
on: push
env:
  NIGHTLY_BRANCH: develop
jobs:
  build-rpm:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-20.04
    container: 'centos:7'
    steps:
      - name: Install vault repos
        run: |
          rm -f /etc/yum.repos.d/*.repo
          cat > /etc/yum.repos.d/CentOS.repo <<EOF
          [base]
          name=CentOS-7.9.2009 - Base
          baseurl=http://vault.centos.org/7.9.2009/os/x86_64/
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
          enabled=1
          metadata_expire=never
          [updates]
          name=CentOS-7.9.2009 - Updates
          baseurl=http://vault.centos.org/7.9.2009/updates/x86_64/
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
          enabled=1
          metadata_expire=never
          [extras]
          name=CentOS-7.9.2009 - Extras
          baseurl=http://vault.centos.org/7.9.2009/extras/x86_64/
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
          enabled=1
          metadata_expire=never
          EOF
      - name: Install dependencies
        run: |
          yum install -y git rpmdevtools rpmlint java-11-openjdk-devel wget
          wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          tar xf apache-maven-3.6.3-bin.tar.gz -C /opt
      - name: Setup build tree
        run: |
          echo "%_topdir $(pwd)/rpmbuild" >> ~/.rpmmacros
          rpmdev-setuptree
          git clone https://github.com/italiangrid/storm-webdav.git rpmbuild/BUILD
          cd rpmbuild/BUILD
          git checkout centos7-rpm
      - name: Calculate version and repo
        run: |
          VERSION='1.5.1'
          REPO='nightly'
          echo "REPO=${REPO}" >> "${GITHUB_ENV}"
          echo "VERSION=${VERSION}" >> "${GITHUB_ENV}"
          echo "Version: ${VERSION}"
          echo "Repo: ${REPO:-none}"
      - name: Build RPM
        run: |
          export PATH=/opt/apache-maven-3.6.3/bin:$PATH
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
          cp rpmbuild/BUILD/storm-webdav.spec rpmbuild/SPECS/storm-webdav.spec
          rpmlint rpmbuild/SPECS/storm-webdav.spec
          rpmbuild --define "base_version ${VERSION}" -ba rpmbuild/SPECS/storm-webdav.spec
      - name: Upload release to repo
        if: env.REPO != ''
        run: |
          curl --fail --user "${{ vars.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" --upload-file rpmbuild/RPMS/noarch/*.rpm https://repo.cloud.cnaf.infn.it/repository/storm-rpm-${REPO}/centos7/
