name: Build and push docker image

on:
  push:
    paths: 
      - docker/**
  pull_request:
    paths: 
      - docker/**

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta for webdav
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: italiangrid/storm-webdav-centos7
          flavor: latest=true
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=tag

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/webdav-centos7
          file: ./docker/webdav-centos7/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}