name: Run testsuite

on:
  push:
#    paths:
#      - robot/**

jobs:
  run-testsuite:
    name: WebDAV test suite

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Fetch crls
        working-directory: compose
        run: docker-compose up trust

      - name: Start WebDAV services
        working-directory: compose
        run: docker-compose up -d webdav nginx

      - name: Run testsuite
        working-directory: compose
        run: |
          docker-compose up -d ts 
          docker-compose exec -T ts bash -c '/scripts/wait-and-run-testsuite.sh'

      - name: Collect test reports
        run: docker cp storm-webdav-ts-1:/home/test/robot/reports .
        
      - name: Stop compose
        if: ${{ always() }}
        working-directory: compose
        run: docker-compose down -v

      - name: Archive reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports
