name: Run testsuite

on:
  push:
    paths:
      - robot/**
      - compose/**
      - docker/**
      - .github/workflows/**

jobs:
  run-testsuite:
    name: WebDAV test suite

    runs-on: ubuntu-latest

    env:
      ARTIFACTS: ${HOME}/artifacts
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Start services
        working-directory: compose
        run: docker-compose up -d

      - name: Run testsuite
        working-directory: compose
        run: |
          set +e
          docker-compose exec -T ts bash -c '/scripts/setup-and-run-testsuite.sh'
          echo "Test suite completed"

      - name: Create artifacts directory
        if: ${{ always() }}
        run: mkdir -p ${ARTIFACTS}

      - name: Collect test reports
        run: docker cp storm-webdav_ts_1:/home/test/robot/reports ${ARTIFACTS}

      - name: Collect service log
        if: ${{ always() }}
        run: docker logs storm-webdav_webdav_1 > ${ARTIFACTS}/storm-webdav-server.log 2>&1

      - name: Archive reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: logs-and-reports
          path: ${{ env.ARTIFACTS }}
