name: Sonar analysis

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    permissions:
      checks: write

    strategy:
      matrix:
        java-version: [11]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK ${{matrix.java-version}}
      uses: actions/setup-java@v1
      with:
        cache: maven
        java-version: ${{matrix.java-version}}

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B clean package -s maven/cnaf-mirror-settings.xml

    - name: Sonar analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -s maven/cnaf-mirror-settings.xml -B -U install sonar:sonar 
            -Dsonar.projectKey=italiangrid_storm-webdav 
            -Dsonar.organization=italiangrid
            -Dsonar.login=$SONAR_TOKEN
            -Dsonar.pullrequest.key=${{ github.event.number }}
            -Dsonar.pullrequest.branch=${{ github.HEAD_REF }}
            -Dsonar.pullrequest.base=${{ github.BASE_REF }}
            -Dsonar.pullrequest.github.repository=${{ github.repository }}
            -Dsonar.scm.provider=git
            -Dsonar.host.url=https://sonarcloud.io